version: "3"
services:

  linux-kernel-build-env:
    build:
      context: ./image
      args:
        HOSTUSER: ${HOSTUSER}
        HOSTUID: ${HOSTUID}
        HOSTGID: ${HOSTGID}
    user: ${HOSTUSER}:${HOSTUSER}
    volumes:
      - /home/arthur/Desktop:/home/${HOSTUSER}/Desktop:rw
