#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
mount -t devtmpfs none /dev


echo "Hello Linux"

ip link set eth0 up
ip address add 192.168.100.101/24 dev eth0

export PATH=$PATH:/usr/bin
exec /bin/bash
